query admin_service {
  serviceAdmin {
    serviceCategoryId {
      id
      name
    }
    price
    name
    description
    timeSlot {
      startDate
      endDate
      startTime
      endTime
    }
    image
    id
  }
}