query admin_service($id: Int) {
  serviceAdmin(id: $id) {
    serviceCategoryId {
      id
      name
    }
    name
    description
    timeSlot {
      startDate
      endDate
      startTime
      endTime
    }
    id
    price
    serviceCategories {
      id
      name
    }
    image
    # imageData
  }
}