query cart_item_category {
	pending: cartItemCategory(status: 0) {
    service {
      name
    }
    date
    time
    status
  }
  paid: cartItemCategory(status: 1) {
    service {
      name
    }
    date
    time
    status
  }
  confirmed: cartItemCategory(status: 2) {
    service {
      name
    }
    date
    time
    status
  }
  cancelled: cartItemCategory(status: 3) {
    service {
      name
    }
    date
    time
    status
  }
  completed: cartItemCategory(status: 3) {
    service {
      name
    }
    date
    time
    status
  }
}