fragment cartItemFields on CartItem {
  service {
    name
    image
    price
  }
  id
  cart {
    id
  }
  date
  time
  status
}

query cart_item_category {
  all: cartItemCategory {
     ...cartItemFields
  }
	pending: cartItemCategory(status: 0) {
    ...cartItemFields
  }
  paid: cartItemCategory(status: 1) {
    ...cartItemFields
  }
  confirmed: cartItemCategory(status: 2) {
    ...cartItemFields
  }
  cancelled: cartItemCategory(status: 3) {
    ...cartItemFields
  }
  completed: cartItemCategory(status: 4) {
    ...cartItemFields
  }
}