mutation create_cart_item($serviceId: ID!, $date: String!, $time: String!) {
  createCartItem(input: {
    serviceId: $serviceId,
    date: $date,
    time: $time
  }) {
    errors
    cartItem {
      id
      date
      time
      status
    }
  }
}
