mutation update_category($id: ID!, $name: String!,
$description: String!, $image: String) {
  updateServiceCategory(input: {
    id: $id,
    name: $name,
    description: $description,
    image: $image
  }) {
    serviceCategory {
      name
      id
      description
    }
    errors
  }
}