mutation create_service_category($name: String!, $description: String!){
  createServiceCategory(input: {
    name: $name,
    description: $description
  }) {
    serviceCategory {
      name
      id
      description
    }
    errors
  }
}