mutation create_service_category($name: String!, $description: String!, $image: String!){
  createServiceCategory(input: {
    name: $name,
    description: $description,
    image: $image
  }) {
    serviceCategory {
      name
      id
      description
      image
    }
    errors
  }
}