query service_by_category($id: ID!) {
  serviceByCategory(id: $id) {
    id
    name
    description
    serviceCategoryId {
      description
      name
    }
    image
    price
    timeSlot {
      id
      startDate
      endDate
      startTime
      endTime
      duration
      interval
      capacity
    }
    cartItemTally {
      date
      count
    }
    cartItem {
      date
      time
    }
  }
}