mutation create_service($serviceCategoryId: ID!, $name: String!,
$description: String!, $price: Int!, $image: String!) {
  createService(input: {
    serviceCategoryId: $serviceCategoryId,
    name: $name,
    description: $description,
    price: $price,
    image: $image
  }) {
    service {
      id
    }
    errors
  }
}